name: Server Demo

on:
    push:
      branches: [master, develop]
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test -- --passWithNoTests
  
      - name: Lint code
        run: npm run lint

      - name: build
        run: npm run build
        
      - name: init git in server directory
        run: git init
        
      - name: Add remote origin
        run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

      - name: Deploy production to Heroku
        run: git subtree push --prefix server origin master