name: Server Demo

on:
    push:
      branches: [master, develop]
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test -- --passWithNoTests
  
      - name: Lint code
        run: npm run lint

      - name: build
        run: npm run build

      - name: Deploy production to Heroku
        uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ts-bootcamp-blackjack-server"
          heroku_email: ${{secrets.HEROKU_EMAIL}}

